[package]
name = "fuse_mt"
version = "0.6.0-dev"
authors = ["William R. Fraser <wfraser@codewise.org>"]
repository = "https://github.com/wfraser/fuse-mt"
description = "A higher-level FUSE filesystem library with multi-threading and inode->path translation."
categories = ["filesystem"]
keywords = ["fuse", "filesystem"]
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
fuse = { git = "https://github.com/zargony/rust-fuse", rev = "f834fbbd5614976e8d480da249d487609504ee6e" }
libc = "0.2"
log = "0.4"
threadpool = "1.0"
time = "0.1"

[workspace]
members = [".", "example"]
